version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  productos-app:
    build:
      context: ./productos-service
      dockerfile: Dockerfile
    container_name: productos-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/appdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      API_KEY: producto
    restart: always

  inventario-app:
    build:
      context: ./inventario-service
      dockerfile: Dockerfile
    container_name: inventario-app
    depends_on:
      - productos-app
      - postgres
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/appdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      PRODUCTOS_API_BASE_URL: http://productos-app:8080/api
      PRODUCTOS_SERVICE_API_KEY: producto
      API_KEY: inventario
    restart: always

volumes:
  postgres_data:
